{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "realtime-svg.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "realtime-svg.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  annotations:
    # WARNING: In-memory Redis - data will be lost on Pod restart
    realtime-svg.io/redis-mode: "in-memory"
    realtime-svg.io/persistence: "disabled"
    {{- with (merge (.Values.redisDeploymentAnnotations | default dict) (.Values.commonAnnotations | default dict)) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "realtime-svg.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "realtime-svg.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        command:
        - redis-server
        {{- if .Values.redis.password }}
        - --requirepass
        - $(REDIS_PASSWORD)
        {{- end }}
        - --save
        - ""
        - --appendonly
        - "no"
        - --maxmemory
        - "256mb"
        - --maxmemory-policy
        - allkeys-lru
        {{- if .Values.redis.password }}
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "realtime-svg.fullname" . }}-secret
              key: redis-password
        {{- end }}
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              {{- if .Values.redis.password }}
              redis-cli -a $REDIS_PASSWORD ping | grep -q PONG
              {{- else }}
              redis-cli ping | grep -q PONG
              {{- end }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
{{- end }}
