{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "realtime-svg.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "realtime-svg.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  {{- with (merge (.Values.redisServiceAnnotations | default dict) (.Values.commonAnnotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    {{- include "realtime-svg.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
