apiVersion: v1
kind: Service
metadata:
  name: {{ include "realtime-svg.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "realtime-svg.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    nodePort: {{ .Values.service.nodePort }}
  {{- else }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- end }}
  selector:
    {{- include "realtime-svg.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
