---
apiVersion: v1
kind: Namespace
metadata:
  name: realtime-svg
  labels:
    app.kubernetes.io/name: realtime-svg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: realtime-svg-config
  namespace: realtime-svg
  labels:
    app.kubernetes.io/name: realtime-svg
    app.kubernetes.io/instance: realtime-svg
    app.kubernetes.io/version: v0.1.4
data:
  REDIS_URL: redis://realtime-svg-redis:6379/
  LOG_LEVEL: info
  PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: realtime-svg-secret
  namespace: realtime-svg
  labels:
    app.kubernetes.io/name: realtime-svg
    app.kubernetes.io/instance: realtime-svg
    app.kubernetes.io/version: v0.1.4
type: Opaque
data: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-svg-redis
  namespace: realtime-svg
  labels:
    app.kubernetes.io/name: realtime-svg
    app.kubernetes.io/instance: realtime-svg
    app.kubernetes.io/version: v0.1.4
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: realtime-svg
      app.kubernetes.io/instance: realtime-svg
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: realtime-svg
        app.kubernetes.io/instance: realtime-svg
        app.kubernetes.io/version: v0.1.4
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        image: redis:8-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        args:
        - --save
        - ""
        - --appendonly
        - "no"
        - --maxmemory
        - 256mb
        - --maxmemory-policy
        - allkeys-lru
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: realtime-svg-redis
  namespace: realtime-svg
  labels:
    app.kubernetes.io/name: realtime-svg
    app.kubernetes.io/instance: realtime-svg
    app.kubernetes.io/version: v0.1.4
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: realtime-svg
    app.kubernetes.io/instance: realtime-svg
    app.kubernetes.io/component: redis
  ports:
  - name: redis
    port: 6379
    targetPort: redis
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-svg
  namespace: realtime-svg
  labels:
    app.kubernetes.io/name: realtime-svg
    app.kubernetes.io/instance: realtime-svg
    app.kubernetes.io/version: v0.1.4
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: realtime-svg
      app.kubernetes.io/instance: realtime-svg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: realtime-svg
        app.kubernetes.io/instance: realtime-svg
        app.kubernetes.io/version: v0.1.4
    spec:
      containers:
      - name: realtime-svg
        image: ghcr.io/egoavara/realtime-svg:v0.1.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: HOST
          value: 0.0.0.0
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: realtime-svg-config
              key: REDIS_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: realtime-svg-config
              key: LOG_LEVEL
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: realtime-svg-config
              key: PORT
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: realtime-svg
  namespace: realtime-svg
  labels:
    app.kubernetes.io/name: realtime-svg
    app.kubernetes.io/instance: realtime-svg
    app.kubernetes.io/version: v0.1.4
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: realtime-svg
    app.kubernetes.io/instance: realtime-svg
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
